### PR TITLE
Prepare 0.0.1 release

### PR DESCRIPTION
**Pull request by fghaas**
I think at this point we are ready for a first tagged release, so unless you're aware of anything that we still absolutely need to include for this to be useful, here's a PR for 0.0.1.

### CODE REVIEW

**Comment by foadlind** [comment]
The only thing I can think of is the ability to add more entries for the `retirement_pipeline` in the [pipeline config file]( https://github.com/hastexo/tutor-contrib-retirement/blob/main/tutorretirement/templates/retirement/build/retirement/pipeline_config/config.yml#L6). I haven't looked at how we can do that with Tutor config parameters yet. Also we probably need to add more Open edX services to the `base_url` part of the pipeline config file.
Should we do those in this release or later?

**Comment by foadlind** [comment]
[Here](https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/user_retire/driver_setup.html#setting-up-the-user-retirement-driver-scripts) you can see an example with more services in the pipeline config file.

**Comment by fghaas** [comment]
> [Here](https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/user_retire/driver_setup.html#setting-up-the-user-retirement-driver-scripts) you can see an example with more services in the pipeline config file.

Ok that looks like a relatively simple exercise to check `{% if ECOMMERCE_HOST is defined %}` (it would only be defined if the [ecommerce plugin](https://github.com/overhangio/tutor-ecommerce) is enabled), and to add the appropriate entries to `config.yml` if set.

As for the credentials service, [as of last year](https://discuss.overhang.io/t/credentials-service-plugin/186/6), nobody had yet written a Tutor plugin, so we probably have to exclude that. It doesn't hurt if we mention it in the README though.

Can you prepare a PR for that?

**Comment by foadlind** [comment]
Ack

**Pull request merged**
